name: DGCMIA
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=2.3.0
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.4.26
  - certifi=2025.4.26
  - importlib-metadata=8.7.0
  - intel-openmp=2023.1.0
  - ld_impl_linux-64=2.40
  - libabseil=20250127.0
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libgrpc=1.71.0
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - markdown=3.8
  - mkl=2023.1.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.4
  - numpy-base=1.26.4
  - openssl=3.0.16
  - packaging=25.0
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.10.12
  - re2=2024.07.02
  - readline=8.2
  - six=1.17.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tensorboard=2.19.0
  - tk=8.6.14
  - tzdata=2025b
  - werkzeug=2.0.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zipp=3.23.0
  - zlib=1.2.13
  - pip:
    - easydict==1.13
    - ftfy==6.3.1
    - fvcore==0.1.5.post20221221
    - grpcio==1.71.0
    - iopath==0.1.10
    - mkl-fft==1.3.11
    - mkl-random==1.2.8
    - mkl-service==2.4.0
    - numpy==1.26.4
    - portalocker==3.1.1
    - prettytable==3.16.0
    - protobuf==6.31.1
    - pyyaml==6.0.2
    - regex==2024.11.6
    - setproctitle==1.3.6
    - setuptools==78.1.1
    - tabulate==0.9.0
    - tensorboard-data-server==0.7.2
    - termcolor==3.1.0
    - tqdm==4.67.1
    - wcwidth==0.2.13
    - wheel==0.45.1
    - yacs==0.1.8
